name: Create a PR

on:
  workflow_call:
  workflow_dispatch:

jobs:
  Make-changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Dependencies
        id: dependencies
        run: 
          npm install cidr-calc
          npm install @actions/core
          npm install prettify-xml
          npm install xml-js

      - name: Set up Git
        run: |
          git config --global user.name "Someone"
          git config --global user.email "someone@somewhere.com"
          
      - name: Track and update github action ip ranges
        id: track-update-profile
        if: ${{steps.dependencies.outcome}} == 'success'
        run: 
          output=$(node scripts/js/checkGithubIpRanges.js)

      - name: Checkout main
        id: get-main
        if: ${{ steps.track-update-profile.outputs.updateNeeded == 'true'}}
        run: |
          git fetch origin main

      - name: create new branch
        id: create-branch
        if: steps.get-main.outcome == 'success'
        run: |
          git checkout -b feature/updated-files main
          echo "Branch 'feature/updated-files' create and pushed successfuly"

      - name: update profile xml
        if: 
        run: echo ${{steps.track-update-profile.outputs.updatedProfile}} >> ./force-app/main/default/profiles/DX Integration Ip test profile.profile-meta.xml
          
      - name: commit changes
        id: commit-changes
        if: steps.new-changes.outcome == 'success'
        run: |
          git add .
          git commit -m "Ip Ranges updated on profile"
          echo "Changes committed successfully"

      - name: Push branch to origin
        id: push-changes
        if: steps.commit-changes.outcome == 'success'
        run: git push --set-upstream origin feature/updated-files --force

      - name: Open Pull Request
        if: steps.push-changes.outcome == 'success'
        run:
          gh pr create -B main -H feature/updated-files --title 'Merge branch_to_merge into base_branch via github action' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: No update required
        if: ${{ steps.run-first-js.outputs.updateNeeded == 'false'}}
        run: echo "Profile up to date with github ip ranges"

