name: Create a PR

on:
  workflow_call:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Someone"
          git config --global user.email "someone@somewhere.com"
          
      - name: Run Js
        id: run-first-js
        run: 
          output=$(node scripts/js/firstJs.js)
          echo "isSuccess = $(output)"

      - name: Ensure 'main' Branch Exists and is Up-to-Date
        run: |
          git fetch origin main

      - name: create new branch
        id: create-branch
        if: ${{ steps.run-first-js.outputs.isSuccess == 'true'}}
        run: |
          git checkout -b feature/updated-files main
          echo "Branch 'feature/updated-files' create and pushed successfuly"

      - name: Run Second JS Script
        id: run-second-js
        if: steps.create-branch.outcome == 'success'
        run: |
          node scripts/js/secondJs.js

      - name: commit changes
        if: steps.run-second-js.outcome == 'success'
        run: |
          git add .
          git commit -m "Commit from action"
          echo "Changes committed successfully"

      - name: Push branch to origin
        if: steps.run-second-js.outcome == 'success'
        run: 
          git push origin feature/updated-files

      - name: Create Pull Request
        if: steps.run-second-js.outcome == 'success'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "File Updated"
          title: "Update File"
          branch: feature/updated-files
          base: main
          body: |
            This file modified then context of newday.txt file.
