name: Create a PR

on:
  workflow_call:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Someone"
          git config --global user.email "someone@somewhere.com"
          
      - name: Run Js
        id: run-first-js
        run: 
          output=$(node scripts/js/firstJs.js)
          echo "isSuccess = ${{ steps.run-first-js.outputs.isSuccess}}"

      - name: Get new changes
        if: ${{ steps.run-first-js.outputs.isSuccess == 'true'}}
        id: new-changes
        run: 
          output=$(node scripts/js/secondJs.js)
          echo "new change = ${{ steps.new-changes.outputs.newChange}}"

      - name: Ensure 'main' Branch Exists and is Up-to-Date
        id: get-main
        if: steps.new-changes.outcome == 'success'
        run: |
          git fetch origin main

      - name: create new branch
        id: create-branch
        if: steps.get-main.outcome == 'success'
        run: |
          git checkout -b feature/updated-files main
          echo "Branch 'feature/updated-files' create and pushed successfuly"

      - name: make changes
        id: make-changes
        run: echo "${{ steps.new-changes.outputs.newChange}}" > ./newDay.txt
          
      - name: commit changes
        id: commit-changes
        if: steps.make-changes.outcome == 'success'
        run: |
          git add .
          git commit -m "Commit from action"
          echo "Changes committed successfully"

      - name: Push branch to origin
        id: push-changes
        if: steps.commit-changes.outcome == 'success'
        run: git push --set-upstream origin feature/updated-files --force

      - name: Create Pull Request
        if: steps.push-changes.outcome == 'success'
        run: 
          gh pr create -B main -H feature/updated-files --title 'Merge feature/updated-files into main' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ github.token }}
